// Writes review/script.md: everything the viewer will hear and see, generated from the video's own data
// (src/script/scenes.ts, src/data/wiring.ts, src/script/order.ts), for the safety review.
// It also enforces the cable rules (exit code 1 if one is broken):
//   R1 nothing is wired while the Arduino USB is plugged in (or the module is on its micro-USB)
//   R2 every scene that plugs in ends unplugged
//   R3 the module goes on micro-USB only while its Gravity cable is not yet connected
//   R4 the capacitor is placed, and its stripe is checked, before the first plug-in after it
//   R5 every bench item is added exactly once, in the step it belongs to
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ITEMS, PINMAP_ROWS, endName, item } from '../src/data/wiring';
import { ORDER, ORDER_TOTAL } from '../src/script/order';
import { SCENES, TROUBLE_ROWS } from '../src/script/scenes';
import { isSay, lineAdds, sayText, Usb } from '../src/script/types';
import { sentences, speakify } from '../src/script/speak';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const out: string[] = [];
const w = (s = '') => out.push(s);
const errors: string[] = [];

const legsText = (id: string) => {
  const it = item(id);
  if ('legs' in it) return Object.entries(it.legs).map(([k, h]) => `${k}: ${h.r.length === 2 ? `${h.r[0] === '+' ? '+' : '−'} rail (col ${h.c})` : `column ${h.c}, row ${h.r}`}`).join('; ');
  if (it.kind === 'wire') return `${it.wire}, ${it.color}: ${endName(it.from)} → ${endName(it.to)}`;
  return 'off the breadboard';
};

w('# Review copy of the Robin build video (generated)');
w();
w('Generated by `scripts/review.ts` from the same data the video renders (`src/script/scenes.ts`, `src/data/wiring.ts`, `src/script/order.ts`). **Do not edit by hand.**');
w('Each spoken line shows the cable state while it is spoken: 🔌 **USB OUT** (Arduino unplugged: the only state in which we wire), ⚡ **USB IN** (testing), 💽 **MICRO** (Arduino unplugged, voice module alone on its micro-USB cable).');
w('"adds" = the parts or wires that appear on the workbench drawing during that line, with their exact holes.');
w();

// ---------- walk the script
let usb: Usb = 'out';
const added = new Map<string, string>();
let capPlacedAt = -1, stripeCheckedAt = -1, idx = 0;
for (const s of SCENES) {
  w(`## ${s.step ? s.step + ' · ' : ''}${s.title}  \`${s.id}\``);
  w(`*${s.part}*`);
  w();
  let pluggedInScene = false;
  s.lines.forEach((l, i) => {
    idx++;
    if (typeof l !== 'string' && l.usb) {
      if (l.usb === 'in') {
        pluggedInScene = true;
        if (capPlacedAt >= 0 && stripeCheckedAt < capPlacedAt) errors.push(`R4 ${s.id}: plugged in after the capacitor was placed, without a stripe check first`);
      }
      if (l.usb === 'micro' && added.has('grav')) errors.push(`R3 ${s.id}: module on micro-USB while its Gravity cable is connected`);
      usb = l.usb;
    }
    const badge = usb === 'out' ? '🔌 USB OUT' : usb === 'in' ? '⚡ USB IN' : '💽 MICRO';
    if (isSay(l)) {
      const cap = sayText(l);
      // R1b: no hands-on fixing while the cable is in (a GND wire brushing the + rail is a short)
      if (usb === 'in' && /\b(move|connect|rewire|swap|bend|push|turn the|put the|check the capacitor)\b/i.test(cap)) errors.push(`R1 ${s.id}: "${cap.slice(0, 60)}…" asks for hands-on work while USB IN`);
      if (/stripe/i.test(cap) && capPlacedAt >= 0) stripeCheckedAt = idx;
      w(`${i + 1}. [${badge}] ${cap}`);
      const spoken = sentences(typeof l === 'string' ? l : l.speak ?? l.say).map(speakify).join(' ');
      if (spoken !== cap) w(`   - *spoken:* "${spoken}"`);
    } else if ('robin' in l) {
      w(`${i + 1}. [${badge}] 🤖 Robin plays its own clip audio/en/${String(l.robin).padStart(2, '0')}.mp3`);
    } else {
      w(`${i + 1}. [${badge}] ⏸ pause ${l.pause} s: ${l.cap ?? 'Pause the video and think'}`);
    }
    for (const a of lineAdds(l)) {
      const it = item(a);
      if (usb !== 'out') errors.push(`R1 ${s.id}: "${a}" is wired while the cable state is ${usb}`);
      if (added.has(a)) errors.push(`R5 ${s.id}: "${a}" added twice (also in ${added.get(a)})`);
      const stepNo = Number((s.step || '').match(/Step (\d)/)?.[1]);
      if (stepNo !== it.step) errors.push(`R5 ${s.id}: "${a}" belongs to step ${it.step}, added in step ${stepNo}`);
      added.set(a, s.id);
      if (a === 'cap') capPlacedAt = idx;
      w(`   - *adds* \`${a}\`: ${it.desc}. (${legsText(a)})`);
    }
  });
  if (pluggedInScene && usb !== 'out') errors.push(`R2 ${s.id}: the scene plugs in but does not end unplugged`);
  if (s.ui && Object.keys(s.ui).length) {
    w();
    w('On-screen text:');
    for (const [k, v] of Object.entries(s.ui)) w(`- \`${k}\`: ${v}`);
  }
  w();
}
for (const it of ITEMS) if (!added.has(it.id)) errors.push(`R5 bench item "${it.id}" is never added in any scene`);

// ---------- tables
w('## Tables shown on screen');
w();
w('### Order (16 lines, = docs/03)');
w('| # | SKU | Qty | Part | € each |');
w('|---|---|---|---|---|');
for (const l of ORDER) w(`| ${l.n} | ${l.sku} | ${l.qty} | ${l.name}${l.isNew ? ` (**${l.isNew}**)` : ''} | ${l.unit.toFixed(2)} |`);
w(`\nTotal parts: €${ORDER_TOTAL.toFixed(2)}`);
w();
w('### Pin map (= docs/04)');
w('| From | To | Wire |');
w('|---|---|---|');
for (const r of PINMAP_ROWS) w(`| ${r.join(' | ')} |`);
w();
w('### Troubleshooting (= docs/04)');
w('| Symptom | Likely cause | Fix |');
w('|---|---|---|');
for (const r of TROUBLE_ROWS) w(`| ${r.join(' | ')} |`);
w();
w('### Every part and wire on the workbench drawing');
w('| id | step | what | where exactly |');
w('|---|---|---|---|');
for (const it of ITEMS) w(`| ${it.id} | ${it.step} | ${it.desc} | ${legsText(it.id)} |`);
w();
w('Drawing notes: the breadboard is drawn with the rail pair next to the Arduino as − inside, + outside, as printed on the drawn board; the video says to follow the red/blue lines printed on the real board. The top rail pair is unused. Modules (PIR, DFR0534, speaker) lie off the board. The DFR0534 is drawn after the board photo in its datasheet (page 2, Voice Module V1.0): Gravity socket T R − + on the left, top holes VCC GND RX TX BUSY, bottom holes ONE DACR DACL SP− SP+, SPK socket on the right. The video says to go by the printed labels.');
w();

// ---------- automatic checks
w('## Automatic checks');
w();
try {
  w(execFileSync('npx', ['tsx', path.join(HERE, 'netcheck.ts'), '--md'], { cwd: ROOT, encoding: 'utf8' }));
} catch (e) {
  const err = e as { stdout?: string };
  w(err.stdout ?? String(e));
  errors.push('netcheck failed (see above)');
}
w();
w(errors.length ? `**Cable-rule check: ${errors.length} problem(s):**\n\n${errors.map((e) => `- ❌ ${e}`).join('\n')}` : '**Cable-rule check: all passed** (R1 nothing wired or moved while plugged in · R2 every test ends unplugged · R3 micro-USB only with the Gravity cable off · R4 capacitor stripe checked before plug-in · R5 every item added once, in its own step).');

fs.mkdirSync(path.join(ROOT, 'review'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'review/script.md'), out.join('\n') + '\n');
console.log(`review/script.md written (${out.length} lines)`);
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
